-- Schema inicial para Supabase PostgreSQL.
create table if not exists concursos (
  id integer generated by default as identity primary key,
  nome varchar(200) not null, cargo varchar(200) not null,
  banca varchar(100) not null default '', edital_url varchar(500),
  edital_text text, created_at timestamptz not null default now()
);
create table if not exists users (
  id integer generated by default as identity primary key,
  username varchar(64) not null unique, full_name varchar(120) not null default '',
  password_hash varchar(200) not null, salt varchar(64) not null,
  role varchar(20) not null default 'aluno' check (role in ('aluno','admin')),
  concurso_id integer references concursos(id) on delete set null
);
create table if not exists sessoes (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  token varchar(64) not null unique, created_at timestamptz not null default now(),
  expires_at timestamptz
);
create table if not exists topicos (
  id integer generated by default as identity primary key,
  concurso_id integer not null references concursos(id) on delete cascade,
  nome varchar(200) not null, pai_id integer references topicos(id) on delete set null,
  ordem integer not null default 0, estudado boolean not null default false
);
create table if not exists blocos (
  id integer generated by default as identity primary key,
  concurso_id integer not null references concursos(id) on delete cascade,
  data date not null default current_date, titulo varchar(200) not null,
  introducao text not null default '', duracao_min integer not null default 60,
  criado_por varchar(40) not null default 'hermes', status varchar(20) not null default 'ativo'
);
create table if not exists questoes (
  id integer generated by default as identity primary key,
  bloco_id integer not null references blocos(id) on delete cascade,
  topico_id integer references topicos(id) on delete set null,
  tipo varchar(20) not null check (tipo in ('mcq','discursiva')),
  enunciado text not null, alternativas jsonb, gabarito varchar(10),
  resposta_modelo text, rubric text, explicacao text, fonte_id integer references fontes(id) on delete set null,
  dificuldade integer not null default 2
);
create table if not exists respostas (
  id integer generated by default as identity primary key,
  questao_id integer not null references questoes(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  resposta text not null, correta boolean, nota double precision,
  feedback text, corrigido_por varchar(40), tempo_seg integer,
  created_at timestamptz not null default now()
);
create table if not exists progresso (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  topico_id integer not null references topicos(id) on delete cascade,
  tentativas integer not null default 0, acertos integer not null default 0,
  dominio double precision not null default 0, ultima_revisao date,
  proxima_revisao date, constraint uq_prog unique (user_id, topico_id)
);
create table if not exists fontes (
  id integer generated by default as identity primary key,
  titulo varchar(300) not null, url varchar(700) not null,
  tipo varchar(40) not null default 'edital', orgao varchar(200), ano integer
);
create table if not exists topicos_fontes (
  topico_id integer not null references topicos(id) on delete cascade,
  fonte_id integer not null references fontes(id) on delete cascade,
  primary key (topico_id, fonte_id)
);
create index if not exists ix_topicos_concurso on topicos(concurso_id, ordem);
create index if not exists ix_blocos_concurso_data on blocos(concurso_id, data);
create index if not exists ix_questoes_bloco on questoes(bloco_id);
create index if not exists ix_respostas_user on respostas(user_id, created_at);
create index if not exists ix_progresso_user_topico on progresso(user_id, topico_id);
