-- Tipos novos são corrigidos pela plataforma sem IA.
alter table public.questoes
  add column if not exists tolerancia double precision,
  add column if not exists unidade varchar(30);

alter table public.questoes drop constraint if exists questoes_tipo_check;
alter table public.questoes add constraint questoes_tipo_check
  check (tipo in ('mcq','discursiva','verdadeiro_falso','numerica'));

-- Conversão segura das discursivas iniciais: não havia respostas históricas.
update public.questoes set tipo='mcq', alternativas='["A) usar recursos com economicidade, produtividade e foco em resultados", "B) aumentar despesas sem avaliar resultados", "C) substituir planejamento por improviso", "D) priorizar formalidade sobre resultados"]'::jsonb, gabarito='0', explicacao='A eficiência exige atuação orientada a resultados e uso adequado dos recursos públicos; não significa gastar mais nem abandonar o planejamento.' where id=19 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) vida, liberdade e igualdade", "B) apenas direitos previstos em contrato privado", "C) somente direitos patrimoniais de empresas", "D) exclusivamente direitos eleitorais"]'::jsonb, gabarito='0', explicacao='Vida, liberdade e igualdade são exemplos de direitos fundamentais previstos na Constituição.' where id=20 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) sistema ou dispositivo que controla tráfego de rede segundo regras de segurança", "B) programa que aumenta a velocidade física do processador", "C) cópia de segurança armazenada em papel", "D) ferramenta que substitui toda autenticação"]'::jsonb, gabarito='0', explicacao='Firewall filtra ou controla o tráfego de rede conforme regras de segurança.' where id=21 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) reduzir o risco de realizar o cuidado na pessoa errada", "B) substituir a prescrição profissional", "C) eliminar a necessidade de registro", "D) permitir compartilhar dados sem critério"]'::jsonb, gabarito='0', explicacao='A identificação correta é uma barreira de segurança para evitar trocas de pacientes e procedimentos.' where id=29 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) acesso universal, cuidado integral e redução de desigualdades conforme necessidades", "B) atendimento somente hospitalar e igual para todos", "C) cobrança proporcional à renda", "D) prioridade exclusiva para serviços privados"]'::jsonb, gabarito='0', explicacao='Universalidade, integralidade e equidade são princípios do SUS.' where id=30 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) participar da assistência conforme sua formação e sob orientação e supervisão do enfermeiro", "B) diagnosticar doenças de forma autônoma", "C) prescrever medicamentos sem habilitação", "D) substituir integralmente o enfermeiro"]'::jsonb, gabarito='0', explicacao='A atuação do técnico deve respeitar sua formação e as atribuições legais, sob orientação e supervisão do enfermeiro.' where id=31 and tipo='discursiva';
update public.questoes set tipo='numerica', alternativas=null, gabarito='15', explicacao='O cálculo é 750 mg × 5 mL ÷ 250 mg = 15 mL.', tolerancia=0.01, unidade='mL' where id=39 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) conferir paciente, medicamento, dose, via, horário, validade e alergias", "B) administrar primeiro e conferir depois", "C) registrar apenas se houver reação", "D) alterar a via conforme preferência pessoal"]'::jsonb, gabarito='0', explicacao='A administração segura exige conferências antes do procedimento.' where id=40 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) limpeza remove sujidade; desinfecção reduz microrganismos; esterilização busca eliminar todas as formas de vida microbiana", "B) limpeza e esterilização são sinônimos", "C) desinfecção sempre remove todos os esporos", "D) esterilização significa apenas retirar sujeira visível"]'::jsonb, gabarito='0', explicacao='Os três processos têm objetivos diferentes; esterilização é o nível mais amplo.' where id=41 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) comprovar doses, orientar o esquema e apoiar a vigilância", "B) substituir a avaliação clínica", "C) dispensar o controle de estoque", "D) impedir a investigação de eventos"]'::jsonb, gabarito='0', explicacao='O registro permite acompanhar o histórico individual e apoiar a vigilância.' where id=48 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) garantir segurança, acionar ajuda, iniciar suporte básico conforme protocolo e usar DEA quando indicado", "B) oferecer líquidos e aguardar", "C) transportar sem avaliar a segurança", "D) iniciar alimentação por via oral"]'::jsonb, gabarito='0', explicacao='A prioridade é segurança, reconhecimento, acionamento de ajuda e suporte básico conforme protocolo.' where id=49 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) acompanhar população adscrita, promover prevenção e coordenar o cuidado na rede", "B) atender apenas situações cirúrgicas", "C) funcionar sem território definido", "D) substituir todos os serviços especializados"]'::jsonb, gabarito='0', explicacao='A equipe atua no território, com cuidado contínuo, prevenção, promoção e coordenação da rede.' where id=50 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) padronizar prioridades e condutas, melhorar comunicação e reduzir omissões", "B) impedir avaliação individual", "C) substituir todos os julgamentos clínicos", "D) permitir qualquer conduta sem registro"]'::jsonb, gabarito='0', explicacao='Protocolos organizam respostas baseadas em evidências e favorecem segurança e comunicação.' where id=51 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) descentralização distribui responsabilidades entre entes; regionalização organiza serviços em territórios e níveis de atenção", "B) ambos significam privatização", "C) descentralização elimina a coordenação", "D) regionalização restringe o cuidado ao hospital"]'::jsonb, gabarito='0', explicacao='Descentralização trata da distribuição de responsabilidades; regionalização articula serviços em territórios.' where id=60 and tipo='discursiva';
update public.questoes set tipo='mcq', alternativas='["A) instância colegiada permanente e deliberativa de participação social, distinta da direção administrativa", "B) unidade hospitalar que executa todos os atendimentos", "C) órgão privado sem usuários", "D) substituto da Secretaria na gestão cotidiana"]'::jsonb, gabarito='0', explicacao='O Conselho exerce participação e controle social; a direção administrativa cabe ao órgão gestor.' where id=61 and tipo='discursiva';
